# -*- coding: utf-8 -*-
"""
Created on Mon Feb 14 15:28:44 2022

@author: austr
"""

import gzip
from Bio import SeqIO
sequence_F1='AGTTGCTGTAGAACTCGTCGATTTCATCCAGCAGCAGGCGAATGCGGTGCTGGGCCCGCTGCAGGCGCTTGCTGGTGCGCACGATGCCGACGTAGTCCCACATGAAGCGCCGCAGTTCGTCCCAGTTGTGCGCAATGATCACGTCCTCGTCCGAGTCGGTCACCTGGCTGGCGTCCCAGCCGGGCAGGGCCTTGGGCATGTCCACTTGCTCCAGGTGCGCCTGGATGTCGGCAGCGGCGG'
sequence_KT2440='AGTTGCTGTAGAACTCGTCGATTTCATCCAGCAGCAGGCGAATGCGGTGCTGGGCCCGCTGCAGGCGCTTGCTGGTGCGCACGATGCCGACGTAGTCCCACATGAAGCGCCGCAGTTCGTCCCAGTTGTGCGCAATGATCACGTCCTCGTCCGAGTCGGTCACCTGGCTGGCGTCCCAGCCGGGCAAGGCCTTGGGCATGGCCACTTGCTCCAGGTGCGCCTGGATGTCGGCAGCGGCGG'
sequence_JM300='AGTTGCTGTAGAACTCGTCGATTTCGTCCAACAGCAGGCGGACTCGGTGCTGGGCGCGCGTCAGGCGCTTGTCGGTGCGGACGATGCCCACGTAGTCCCACATGAACCGCCGCAGCTCGTCCCAGTTGTGAGCGATGATCACGTCTTCATCCGAGTTGGTGACCTGGCTGGCGTCCCATTGCGGAAGGTTGGTCGGTCCGTCGATTTCCGGTAGCTCGCGCAGGATGTCGCGTGCGGCGG'
sequence_DC3000='AGTTGCTGTAGAACTCATCAATTTCGTCGAGCAACAACCGCACACGGTGCTGGGCGCGCTGCAAGCGTTTGTTGGTGCGCACGATACCGACGTAATCCCACATGAACCTCCTTAATTCGTCCCAGTTGTGGGCGATGATCACGTCTTCGTCCGAGTCGGTTACCTGGCTGGCATCCCACGCTGGCAGGTCAGTCGGCATCGGCACACTGGACAACTGCTTTTCGATGTCTGCGGCTGCCG'
number_total=0
number_F1=0
number_KT2440=0
number_JM300=0
number_DC3000=0
with gzip.open("Control-6_R1_001.fastq.gz", "rt") as handle:
    for record in SeqIO.parse(handle, "fastq"):
        sequence=record.seq
        for n in range(8):
            if sequence[n]=='A' and sequence[n+1]=='G' and sequence[n+2]=='T' and sequence[n+3]=='T':
                sequence_new=sequence[n:n+240]
                number_total=number_total+1
                if sequence_new==sequence_F1:
                    number_F1=number_F1+1
                if sequence_new==sequence_KT2440:
                    number_KT2440=number_KT2440+1
                if sequence_new==sequence_JM300:
                    number_JM300=number_JM300+1
                if sequence_new==sequence_DC3000:
                    number_DC3000=number_DC3000+1
                continue
print(number_total)
print(number_F1+number_KT2440+number_JM300+number_DC3000)
print(number_F1)
print(number_KT2440)
print(number_JM300)
print(number_DC3000)